### ISSUE TITLE
Use Checkstyle in the project.

### ISSUE THREAD

**Issue by sravanreddy001** [shashankreddy509/Bullian-Tracker#1]
**What is Checkstyle**
Checkstyle is a development tool to help programmers write Java code that adheres to a coding standard.

**How to Use**
http://www.androidenea.com/2010/04/using-checkstyle-with-android-open.html
**Example file** https://gist.github.com/shareme/948425 - and this
**Gradle Plugin** - https://github.com/nrudenko/gradle-android-cq-plugin

**Comment by shashankreddy509** [comment]
Added the Check style to the project and committed.
