### ISSUE TITLE
Organize the Code into appropriate Java Packages

### ISSUE THREAD

**Issue by sravanreddy001** [shashankreddy509/Bullian-Tracker#5]
Things to address:
1. Base package name - User your name - What is techradicle? - http://techradicle.com/ (is already used)
2. all other files into appropriate package structure - With package names always in lower-case (JavaStandards)

**Comment by shashankreddy509** [comment]
http://techradicle.com/ is my site.

**Comment by shashankreddy509** [comment]
Updated the package names to lower case.

**Comment by sravanreddy001** [comment]
Cool. Who created this article?
http://techradicle.com/2015/06/07/gradle-with-android

**Comment by shashankreddy509** [comment]
i only created it
