### ISSUE TITLE
Enable Reviewable.io for Code Reviews

### ISSUE THREAD

**Issue by sravanreddy001** [shashankreddy509/Bullian-Tracker#6]
https://reviewable.io/repositories

-Enabled for Bullian Tracker application.

**Comment by shashankreddy509** [comment]
Enabled reviewable for Bullian Tracker.

**Comment by sravanreddy001** [comment]
I provided a clear link and what is expected. 
Provide a link.
Did you ensure that the requester has permissions to review them? - 
If unsure - Don't close the issue.
